# Generated by Django 5.2.5 on 2025-09-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examsubmission",
            name="question_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
